apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: candidate-api-dev

resources:
  - namespace.yaml
  - ../../base

labels:
  - pairs:
      app.kubernetes.io/instance: candidate-api-dev
    includeSelectors: false

patches:
  - path: configmap-patch.yaml

replicas:
  - name: candidate-api
    count: 1
