apiVersion: v1
kind: ConfigMap
metadata:
  name: candidate-api-config
  labels:
    app.kubernetes.io/name: candidate-api
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  CandidateApi__Region: "us-central-1"
