apiVersion: v1
kind: Service
metadata:
  name: candidate-api
  labels:
    app.kubernetes.io/name: candidate-api
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: candidate-api
  ports:
    - name: http
      port: 80
      targetPort: http
